export const PUSH_MUTATION = 'PUSH_MUTATION'
export const SHIFT_MUTATION = 'SHIFT_MUTATION'
export const LOCK_MUTATION_QUEUE = 'LOCK_MUTATION_QUEUE'
export const UNLOCK_MUTATION_QUEUE = 'UNLOCK_MUTATION_QUEUE'
